/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UiRouteImport } from './routes/ui'
import { Route as AccountContactsRouteImport } from './routes/account_.contacts'
import { Route as AccountProfileRouteImport } from './routes/account_.profile'
import { Route as AccountProviderRouteImport } from './routes/account_.provider'
import { Route as AccountServicesRouteImport } from './routes/account_.services'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as ChatsConversationIdRouteImport } from './routes/chats.$conversationId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as ServicesServiceIdRouteImport } from './routes/services_.$serviceId'
import { Route as SigninVerifyRouteImport } from './routes/signin_.verify'
import { Route as AccountServicesServiceIdRouteImport } from './routes/account_.services_.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountContactsRoute = AccountContactsRouteImport.update({
  id: '/account_/contacts',
  path: '/account/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account_/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProviderRoute = AccountProviderRouteImport.update({
  id: '/account_/provider',
  path: '/account/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountServicesRoute = AccountServicesRouteImport.update({
  id: '/account_/services',
  path: '/account/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRoute,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatsRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services_/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninVerifyRoute = SigninVerifyRouteImport.update({
  id: '/signin_/verify',
  path: '/signin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountServicesServiceIdRoute =
  AccountServicesServiceIdRouteImport.update({
    id: '/account_/services_/$serviceId',
    path: '/account/services/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/chats': typeof ChatsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/publish': typeof PublishRoute
  '/services': typeof ServicesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/ui': typeof UiRoute
  '/account/contacts': typeof AccountContactsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/provider': typeof AccountProviderRoute
  '/account/services': typeof AccountServicesRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/signin/verify': typeof SigninVerifyRoute
  '/chats/': typeof ChatsIndexRoute
  '/account/services/$serviceId': typeof AccountServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/favorites': typeof FavoritesRoute
  '/publish': typeof PublishRoute
  '/services': typeof ServicesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/ui': typeof UiRoute
  '/account/contacts': typeof AccountContactsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/provider': typeof AccountProviderRoute
  '/account/services': typeof AccountServicesRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/signin/verify': typeof SigninVerifyRoute
  '/chats': typeof ChatsIndexRoute
  '/account/services/$serviceId': typeof AccountServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/chats': typeof ChatsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/publish': typeof PublishRoute
  '/services': typeof ServicesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/ui': typeof UiRoute
  '/account_/contacts': typeof AccountContactsRoute
  '/account_/profile': typeof AccountProfileRoute
  '/account_/provider': typeof AccountProviderRoute
  '/account_/services': typeof AccountServicesRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/services_/$serviceId': typeof ServicesServiceIdRoute
  '/signin_/verify': typeof SigninVerifyRoute
  '/chats/': typeof ChatsIndexRoute
  '/account_/services_/$serviceId': typeof AccountServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/chats'
    | '/favorites'
    | '/publish'
    | '/services'
    | '/signin'
    | '/signup'
    | '/ui'
    | '/account/contacts'
    | '/account/profile'
    | '/account/provider'
    | '/account/services'
    | '/chats/$conversationId'
    | '/profile/$userId'
    | '/services/$serviceId'
    | '/signin/verify'
    | '/chats/'
    | '/account/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/favorites'
    | '/publish'
    | '/services'
    | '/signin'
    | '/signup'
    | '/ui'
    | '/account/contacts'
    | '/account/profile'
    | '/account/provider'
    | '/account/services'
    | '/chats/$conversationId'
    | '/profile/$userId'
    | '/services/$serviceId'
    | '/signin/verify'
    | '/chats'
    | '/account/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/chats'
    | '/favorites'
    | '/publish'
    | '/services'
    | '/signin'
    | '/signup'
    | '/ui'
    | '/account_/contacts'
    | '/account_/profile'
    | '/account_/provider'
    | '/account_/services'
    | '/chats/$conversationId'
    | '/profile/$userId'
    | '/services_/$serviceId'
    | '/signin_/verify'
    | '/chats/'
    | '/account_/services_/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  PublishRoute: typeof PublishRoute
  ServicesRoute: typeof ServicesRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  UiRoute: typeof UiRoute
  AccountContactsRoute: typeof AccountContactsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountProviderRoute: typeof AccountProviderRoute
  AccountServicesRoute: typeof AccountServicesRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  SigninVerifyRoute: typeof SigninVerifyRoute
  AccountServicesServiceIdRoute: typeof AccountServicesServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/contacts': {
      id: '/account_/contacts'
      path: '/account/contacts'
      fullPath: '/account/contacts'
      preLoaderRoute: typeof AccountContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/profile': {
      id: '/account_/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/provider': {
      id: '/account_/provider'
      path: '/account/provider'
      fullPath: '/account/provider'
      preLoaderRoute: typeof AccountProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/services': {
      id: '/account_/services'
      path: '/account/services'
      fullPath: '/account/services'
      preLoaderRoute: typeof AccountServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/chats/$conversationId': {
      id: '/chats/$conversationId'
      path: '/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$serviceId': {
      id: '/services_/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin_/verify': {
      id: '/signin_/verify'
      path: '/signin/verify'
      fullPath: '/signin/verify'
      preLoaderRoute: typeof SigninVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/services_/$serviceId': {
      id: '/account_/services_/$serviceId'
      path: '/account/services/$serviceId'
      fullPath: '/account/services/$serviceId'
      preLoaderRoute: typeof AccountServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatsRouteChildren {
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsConversationIdRoute: ChatsConversationIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ChatsRoute: ChatsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  PublishRoute: PublishRoute,
  ServicesRoute: ServicesRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  UiRoute: UiRoute,
  AccountContactsRoute: AccountContactsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountProviderRoute: AccountProviderRoute,
  AccountServicesRoute: AccountServicesRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  SigninVerifyRoute: SigninVerifyRoute,
  AccountServicesServiceIdRoute: AccountServicesServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
